# Generated by Django 4.1 on 2022-08-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_model',
            name='gifs',
            field=models.ManyToManyField(related_name='categories', to='gifs.gif_model'),
        ),
    ]
