# Generated by Django 4.1 on 2022-08-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
