# Generated by Django 4.1 on 2022-08-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0003_alter_userprofile_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hobbies',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
