# Generated by Django 4.1 on 2022-08-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0012_remove_userprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='users_friends', to='chatApp.friend'),
        ),
    ]
