# Generated by Django 4.1 on 2022-08-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0013_userprofile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
