# Generated by Django 4.1 on 2022-08-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0014_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='blankprofilephoto.jpeg', null=True, upload_to='profile_images'),
        ),
    ]
