# Generated by Django 4.1 on 2022-08-29 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0021_remove_friendrequest_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 29, 7, 50, 50, 257890, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
